package be.ugent.devops.services.logic.api;

public enum UnitMoveType {
    TRAVEL, CONQUER_NEUTRAL_TILE, NEUTRALIZE_ENEMY_TILE, GENERATE_GOLD, ATTACK, PREPARE_DEFENSE, FORTIFY, PRAY, HEAL,
    CONVERT, DEPLOY_BOMB, CLEAR_BOMB, RETIRE, IDLE
}
