-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/655471223
SELECT CUSTOMER.NAME, PURCHASE_ORDER.QUANTITY, PURCHASE_ORDER.SALES_DATE
FROM CUSTOMER, PURCHASE_ORDER 
WHERE CUSTOMER.CUSTOMER_ID = PURCHASE_ORDER.CUSTOMER_ID AND (CUSTOMER.NAME LIKE 'B%' OR CUSTOMER.NAME LIKE 'J%') AND PURCHASE_ORDER.QUANTITY >= 100


