-- https://dodona.ugent.be/nl/courses/1032/series/11421/activities/114990394
SELECT PRODUCT.DESCRIPTION AS PRODUCT_DESCRIPTION, PRODUCT_CODE.DESCRIPTION AS PRODUCTCODE_DESCRIPTION
FROM PRODUCT, PRODUCT_CODE
WHERE PRODUCT.PRODUCT_CODE = PRODUCT_CODE.PROD_CODE
ORDER BY PRODUCT.PRODUCT_CODE, PRODUCT_CODE.DESCRIPTION


