-- https://dodona.ugent.be/nl/courses/1032/series/11421/activities/606978853
SELECT DISCOUNT_CODE.RATE, PRODUCT_CODE.DESCRIPTION 
FROM PRODUCT_CODE, DISCOUNT_CODE
WHERE PRODUCT_CODE.DISCOUNT_CODE = DISCOUNT_CODE.DISCOUNT_CODE



