-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/181954632
SELECT COUNT(DISTINCT MANUFACTURER.NAME)
FROM MANUFACTURER, PRODUCT, PURCHASE_ORDER
WHERE MANUFACTURER.MANUFACTURER_ID = PRODUCT.MANUFACTURER_ID AND PURCHASE_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID AND QUANTITY > 0
