-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/1417550907
SELECT CUSTOMER.NAME, MAX(QUANTITY) AS MAXIMUM
FROM CUSTOMER, PURCHASE_ORDER
WHERE CUSTOMER.CUSTOMER_ID = PURCHASE_ORDER.CUSTOMER_ID AND PURCHASE_ORDER.QUANTITY IS NOT NULL
GROUP BY NAME
ORDER BY MAXIMUM DESC


