-- https://dodona.ugent.be/nl/courses/1032/series/11421/activities/2107768711
SELECT CUSTOMER.NAME, DISCOUNT_CODE.RATE
FROM CUSTOMER, DISCOUNT_CODE
WHERE CUSTOMER.DISCOUNT_CODE = DISCOUNT_CODE.DISCOUNT_CODE

