-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/80384076
SELECT PRODUCT_CODE.DESCRIPTION, SUM(QUANTITY)
FROM PRODUCT_CODE, PRODUCT, PURCHASE_ORDER
WHERE PRODUCT_CODE.PROD_CODE = PRODUCT.PRODUCT_CODE AND PRODUCT.PRODUCT_ID = PURCHASE_ORDER.PRODUCT_ID 
GROUP BY PRODUCT_CODE.DESCRIPTION
HAVING SUM(PURCHASE_ORDER.QUANTITY) > 500
ORDER BY PRODUCT_CODE.DESCRIPTION
