-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/1984068462
SELECT MANUFACTURER.NAME
FROM MANUFACTURER, PRODUCT, PURCHASE_ORDER, CUSTOMER
WHERE MANUFACTURER.MANUFACTURER_ID = PRODUCT.MANUFACTURER_ID AND PRODUCT.PRODUCT_ID = PURCHASE_ORDER.PRODUCT_ID AND PURCHASE_ORDER.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID AND CUSTOMER.NAME IS 'New Enterprises'

