-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/400495191
SELECT PRODUCT.DESCRIPTION, SUM(QUANTITY)*PRODUCT.PURCHASE_COST AS TOTAAL, SUM(QUANTITY) AS AANTAL_BESTELD
FROM PRODUCT, PURCHASE_ORDER
WHERE PRODUCT.PRODUCT_ID = PURCHASE_ORDER.PRODUCT_ID 
GROUP BY PRODUCT.DESCRIPTION
HAVING SUM(QUANTITY)*PRODUCT.PURCHASE_COST > 50000
ORDER BY TOTAAL DESC

