-- https://dodona.ugent.be/nl/courses/1032/series/11421/activities/1153980697
SELECT PRODUCT.DESCRIPTION, DISCOUNT_CODE.RATE
FROM PRODUCT, PRODUCT_CODE, DISCOUNT_CODE
WHERE PRODUCT.PRODUCT_CODE = PRODUCT_CODE.PROD_CODE AND PRODUCT_CODE.DISCOUNT_CODE = DISCOUNT_CODE.DISCOUNT_CODE

