-- https://dodona.ugent.be/nl/courses/1032/series/11422/activities/1891861065
SELECT DISTINCT PRODUCT_CODE.DESCRIPTION
FROM PRODUCT_CODE, PRODUCT, PURCHASE_ORDER, CUSTOMER
WHERE PRODUCT_CODE.PROD_CODE = PRODUCT.PRODUCT_CODE AND PRODUCT.PRODUCT_ID = PURCHASE_ORDER.PRODUCT_ID AND PURCHASE_ORDER.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID AND CUSTOMER.ZIP LIKE '95%' AND PURCHASE_ORDER.QUANTITY > 0
ORDER BY PRODUCT_CODE.DESCRIPTION DESC