-- https://dodona.ugent.be/nl/courses/1032/series/11417/activities/645593457
SELECT DESCRIPTION, PRODUCT_CODE, CITY, STATE
FROM PRODUCT, MANUFACTURER
WHERE PRODUCT.MANUFACTURER_ID = MANUFACTURER.MANUFACTURER_ID AND QUANTITY_ON_HAND < 500


