-- https://dodona.ugent.be/nl/courses/1032/series/11417/activities/2109472782
SELECT CUSTOMER.NAME, PRODUCT.DESCRIPTION
FROM CUSTOMER, PURCHASE_ORDER, PRODUCT, MANUFACTURER
WHERE CUSTOMER.CUSTOMER_ID = PURCHASE_ORDER.CUSTOMER_ID AND PURCHASE_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID AND PRODUCT.MANUFACTURER_ID = MANUFACTURER.MANUFACTURER_ID AND MANUFACTURER.CITY LIKE 'San%'
ORDER BY CUSTOMER.NAME 

