-- https://dodona.ugent.be/nl/courses/1032/series/11417/activities/1028495853
SELECT PRODUCT_CODE, MIN(PURCHASE_COST), MAX(PURCHASE_COST)
FROM PRODUCT
WHERE AVAILABLE IS 'TRUE'
GROUP BY PRODUCT_CODE




