-- https://dodona.ugent.be/nl/courses/1032/series/11417/activities/1194952526
SELECT PRODUCT_CODE.DESCRIPTION, SUM(QUANTITY) 
FROM PRODUCT, PURCHASE_ORDER, PRODUCT_CODE
WHERE  PRODUCT.PRODUCT_ID = PURCHASE_ORDER.PRODUCT_ID AND PRODUCT.PRODUCT_CODE = PRODUCT_CODE.PROD_CODE 
GROUP BY PRODUCT.PRODUCT_CODE
HAVING SUM(QUANTITY) > 500