apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-deployment
  labels:
    app: logic
    app.kubernetes.io/name: logic-service
spec:
  selector:
    matchLabels:
      app: logic
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
      - name: logic-service
        image: gitlab.stud.atlantis.ugent.be:5050/devops-2024/devops-team12/logic-service
        ports:
        - containerPort: 8080
        - name: metrics
          containerPort: 9000
          protocol: TCP

        env:
          - name: SECURE_ENDPOINTS
            value: "true"
          - name: SECURE_KEY
            valueFrom:
              secretKeyRef:
                name: secure-key-secret
                key: secure-key

        volumeMounts:
          - mountPath: /mnt/game-state
            name: game-state-volume
      volumes:
        - name: game-state-volume
          persistentVolumeClaim:
            claimName: logic-service-pvc
      # More on this later:
      imagePullSecrets:
      - name: gitlab-credentials