kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logic-service-pvc
  labels:
    app: logic
spec:
  storageClassName: k8s-stud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi